FROM python

WORKDIR /home

ADD mascarar_dados.py .

#felizmente, o hashlib e sys já vem na imagem do pyton, nã osendo nescessario instalação

ENTRYPOINT ["python","mascarar_dados.py"]

CMD ["python","mascarar_dados.py"]


